### ISSUE TITLE
query failes in dmsf 2.4.7

### ISSUE THREAD

**Issue by teatower** [danmunn/redmine_dmsf#1276] opened 2021-08-04 10:48 UTC
Hello,
thank your for this superb plugin.

Today I upgraded from redmine 4.1.1 to 4.2.2.
In this conext I also upgraded to the newest dmsf-version.

Although I grant 777 to redminehome$/files and to redminehome$/files/dmsf the access to the dmsf-tab within any project is blocked.

redmine-error logs states:
`
Query::StatementInvalid (Mysql2::Error: Illegal mix of collations for operation 'UNION': SELECT COUNT(*) FROM ( (SELECT
        dmsf_folders.id AS id,
        dmsf_folders.project_id AS project_id,
        CAST(NULL AS signed) AS revision_id,
        dmsf_folders.title AS title,
        NULL AS filename,
        CAST(NULL AS signed) AS size,
        dmsf_folders.updated_at AS updated,
        CAST(NULL AS signed) AS major_version,
        CAST(NULL AS signed) AS minor_version,
        CAST(NULL AS signed) AS workflow,
        CAST(NULL AS signed) AS workflow_id,
        users.firstname AS firstname,
        users.lastname AS lastname,
        users.id AS author,
        'folder' AS type,
        dmsf_folders.deleted AS deleted,
        1 AS sort  FROM `dmsf_folders` LEFT JOIN users ON dmsf_folders.user_id = users.id WHERE (1=0)) UNION ALL (SELECT
      projects.id AS id,
      projects.id AS project_id,
      CAST(NULL AS signed) AS revision_id,
      projects.name AS title,
      projects.identifier AS filename,
      CAST(NULL AS signed) AS size,
      projects.updated_on AS updated,
      CAST(NULL AS signed) AS major_version,
      CAST(NULL AS signed) AS minor_version,
      CAST(NULL AS signed) AS workflow,
      CAST(NULL AS signed) AS workflow_id,
      '' AS firstname,
      '' AS lastname,
      CAST(NULL AS signed) AS author,
      'project' AS type,
      CAST(0 AS signed) AS deleted,
      0 AS sort  FROM `projects` WHERE (projects.status <> 9) AND `projects`.`parent_id` IS NULL) ) `dmsf_folders`):
`

When going back to 4.1.1 (still existend on the same system), I can access dmsf and get the files listed (although redminehomeOLD$/files/dmsf is full of folders (p_name-of-project) but these folders are empty.)

I would be very grateful for any help given. 
Thank you very much!

**Comment by picman** [comment] 2021-08-09 12:52
The error in the log has nothing to do with files permissions. The problem is in your database: `Mysql2::Error: Illegal mix of collations`.

**Comment by teatower** [comment] 2021-08-09 13:04
Thank you, Karel for your reply, I very much appreciate that.

I upgraded redmine, I did the migration tasks, I installed the plugin as described (and as successfully done before), and now I get this malfunctioning. Do you have any hint for me?

Thank you for your efforts and this plugin!

Kind regards,
teatower

**Comment by picman** [comment] 2021-08-10 06:49
Test the query directly in your database and simplify the query step by step until you identify columns which make troubles.

e.g.:
```sql
mysql> SELECT dmsf_folders.id AS id, dmsf_folders.title AS title FROM dmsf_folders  UNION  SELECT projects.id AS id, projects.name AS title FROM projects;
```
Check the collation of your tables. They should be equal.

e.g.:
```sql
mysql> show create table dmsf_folders;
mysql> show create table dmsf_files;
mysql> show create table dmsf_links;
mysql> show create table projects;
```

**Comment by picman** [comment] 2021-08-31 10:55
No feedback => closing.

**Closed by picman** 2021-08-31 10:55 UTC
Labels: wontfix

**Comment by teatower** [comment] 2021-08-31 11:45
Karel, sorry for not getting back to you. That was very unfriendly, please excuse me.
I followed your advise but my skills were not sufficient enough to take advantage of it. I am familiar with databases but not with ruby/rails.
I finally decided to withdraw my upgrade of redmine 4.2.2 back to 4.2.1 and after that did all upgrade steps again.
Luckily this time all went well and I can take advantage of the up-to-date redmine and your plugin. Although I have not upgraded to the newest dmsf-version 2.4.2 (too afraid it could fail).
Sorry again.
Thanks,
teatower

**Comment by picman** [comment] 2021-08-31 11:53
I'd recommend installing another server/virtual machine to test new versions.
