### ISSUE TITLE
can't see files via WebDav, but see them via web-portal

### ISSUE THREAD

**Issue by mkulgin** [danmunn/redmine_dmsf#827] opened 2018-02-09 10:17 UTC
First of all - thanks for the plugin! Really Perfect. But there is a issue - users can easily work with files in folders via redmine webportal, but when they connect to the same folders via WebDav (Windows 10) - the folders are empty (they can see the folders and go inside the folders, but they can't see the files)! Any idea? :) Yes, WebDav support is enable in DMSF module configuration. 

p.s. files we upload via REST API of DMSF.

Thanks!

**Comment by picman** [comment] 2018-02-09 13:27
- I can't test it as I don't have Windows 10, sorry.
- Have you tried another WebDAV client except Windows embedded?
- Is there something in the production.log?
- Can you try the branch 1.6.1-devel. There's a lot of improvement related to WebDAV.

**Comment by mkulgin** [comment] 2018-02-10 17:39
The problem seems to be related "_" character in the folder name :) (yes it may sound strange)...
Thanks I will try 1.6.1. - can I deploy it on production server (we have bitnami redmine 3.4 windows)? Is there a instruction how to upgrade dfms?

**Comment by picman** [comment] 2018-02-12 07:06
No, I can't recommend using neither 1.6.1. on a production server nor Windows. Upgrade is quite easy:
```
cd redmine_dmsf
git fetch
git checkout devel-1.6.1
chown -R www-data:www-data *
cd ..
bundle install
bundle exec rake redmine:plugins:migrate RAILS_ENV=production
```

**Comment by mkulgin** [comment] 2018-02-14 10:16
Well, unfortunately the problems remains :(

**Comment by mkulgin** [comment] 2018-02-14 10:32
Well, the problems still remains.

1. we upload a file via restAPI
2. user login an he can see the file via web (https://prnt.sc/iejio5) (btw - sometimes the file size not visible).
3. the same user log in via webdav (windows10) and ... he dosn't see and folders at all. At the same time - on MacOS it works well :)

and that problem seems to exist for any files downloaded via RestAPI.

**Comment by mkulgin** [comment] 2018-02-14 10:56
Update... if user download a file (uploaded earlier via rest api), remove it from the dmsf via web and upload the file again (via web), then he can work well with the file via WebDav on Windows. An the DMSF remove "_" character from the name https://prnt.sc/iek03s while uploading!

so I guess that Windows WebDav for some reason dosen't support the "_" in the file name in DMSF...

**Comment by picman** [comment] 2018-02-14 11:05
The problem is in the zero size. I'll fix it.

**Comment by mkulgin** [comment] 2018-02-14 11:13
how can we continue working with upload files via Rest API right now?

**Comment by picman** [comment] 2018-02-14 11:27
I've just fixed in _master_ and _devel-1.6.1_ branches. So if you use the master branch, just call `git pull` in the plugin directory.

**Comment by mkulgin** [comment] 2018-02-14 11:31
no. we use 1.6.0 on Bitnami Redmine Windows. And I don't understand how to download and deploy the 1.6.1 :) I have downloaded ZIP file from GitHub and installed the plugin (1.6.0). It is not a problem to download 1.6.1 and install it (upgrade)- but HOW to get it? :)

**Comment by picman** [comment] 2018-02-14 11:53
Do not use 1.6.1 in a production environment. There is a lot of new things not yet tested. In your case download 1.6.0 ZIP again. It's fixed there now. (It's not optimal solution but despite all recommendations I update an already released version in case of serious bugs.)
For next usage I'd recommend Redmine/Linux and git clone/pull for the plugin downloading/upgrading. Your work will be easier, I think.

**Closed by picman** 2018-02-14 11:53 UTC
Labels: type: bug

**Comment by picman** [comment] 2018-02-14 12:15
Or just see the commit https://github.com/danmunn/redmine_dmsf/commit/d92f8745ee34bf162ab064bb7b098db1542f42a1 and fix it locally.
