### ISSUE TITLE
Create symbolic link from another project

### ISSUE THREAD

**Issue by mrak0s** [danmunn/redmine_dmsf#963] opened 2019-01-28 11:18 UTC
In issues section, trying to add link to file from another project, I'm receiving next error:

**Production log:**

> Started GET "/dmsf_links/p19001/autocomplete_for_project.js?utf8=%E2%9C%93&dmsf_link%5Bproject_id%5D=5&dmsf_link%5Btype%5D=link_from&dmsf_link%5Bdmsf_file_id%5D=&dmsf_link%5Bcontainer%5D=Issue&dmsf_link%5Btarget_project_id%5D=6&dmsf_link%5Btarget_folder_id%5D=Documents&dmsf_link%5Btarget_file_id%5D=&dmsf_link%5Bname%5D=" for 192.168.206.1 at 2019-01-28 10:32:57 +0000
> Processing by DmsfLinksController#autocomplete_for_project as JS
>   Parameters: {"utf8"=>"✓", "dmsf_link"=>{"project_id"=>"5", "type"=>"link_from", "dmsf_file_id"=>"", "container"=>"Issue", "target_project_id"=>"6", "target_folder_id"=>"Documents", "target_file_id"=>"", "name"=>""}, "id"=>"p19001"}
>   Current user: admin (id=1)
>   Rendered plugins/redmine_dmsf/app/views/dmsf_links/autocomplete_for_project.js.erb (4.7ms)
> Completed 500 Internal Server Error in 17ms (ActiveRecord: 5.4ms)
> 
> ActionView::Template::Error (undefined method `id' for "6":String):
>     2: 
>     3: link.html('<%= escape_javascript(
>     4:   select_tag('dmsf_link[target_folder_id]',
>     5:          folder_tree_options_for_select(DmsfFolder.directory_tree(params[:dmsf_link][:target_project_id])))) %>');
>     6: link.change();
>   plugins/redmine_dmsf/app/models/dmsf_folder.rb:205:in `directory_tree'
>   plugins/redmine_dmsf/app/views/dmsf_links/autocomplete_for_project.js.erb:5:in `_plugins_redmine_dmsf_app_views_dmsf_links_autocomplete_for_project_js_erb___809377069193573863_47395373363260'
>   plugins/redmine_dmsf/app/controllers/dmsf_links_controller.rb:74:in `autocomplete_for_project'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>   plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:68:in `call'

**Versions:**

> Environment:
>   Redmine version                3.4.6.stable
>   Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
>   Rails version                  4.2.8
>   Environment                    production
>   Database adapter               Mysql2
> SCM:
>   Subversion                     1.9.5
>   Git                            2.11.0
>   Filesystem                     
> Redmine plugins:
>   project_section                0.1.0
>   redmine_dmsf                   1.6.2
>   redmine_enforce_time_entry     0.7.0

**Comment by mrak0s** [comment] 2019-01-29 08:11
I confirm that it is possible to add link from current project after fixing #959. But then you try to select like "Source project " any other project field for selecting folder remain always pointed to current project.

**Comment by picman** [comment] 2019-01-30 11:40
I can't reproduce such behaviour. If I change the project, the folder pick list is always updated. Check whether Javascript is enabled in your browser and check the Javascript console for any errors.

**Comment by picman** [comment] 2019-02-19 07:49
No feedback => closing

**Closed by picman** 2019-02-19 07:49 UTC
Labels: duplicate
