### ISSUE TITLE
Access rights to read (maybe write) individual folders

### ISSUE THREAD

**Issue by i-and** [danmunn/redmine_dmsf#639] opened 2017-01-19 22:36 UTC
Hi!
Could You in future versions of the plugin to implement access rights to read (maybe write) individual folders (as is done in SVN, or by analogy ideology WhiteLists from the Redmine Knowledgebase plugin)? Now we have to create separate projects with one active module DMSF and project rights Reder and Writer. It is not very convenient. 
As DMSF does not support displaying the structure of the projects folder via WebDAV, WebDAV seems a large number of projects without the necessary hierarchy. The introduction of access rights at the folder level would solve this problem too.
Maybe there are other solution? 
Thanks in advance.

**Comment by DarkSideGeek** [comment] 2017-01-20 02:14
We have a large number of projects (each with their own unique roles/access). What I *wish* we had done was to have DMSF in each. And if DMSF supported role-based access control (RBAC) on the folder structure, we'd be ecstatic. 

But what we did instead was create one big giant Doc project that stores all files associated with the hundreds of projects, and gave everyone access. Now we have people with theoretically no need-to-know for certain things, yet they do. Would DMSF ACLs solve that problem? Sure, but wouldn't it be duplicative to the roles structure? I'd prefer RBAC. 

Now that doesn't mean that the multiple WebDAV mount points isn't an issue. I think that's a fair point. But maybe that sub-problem should be tackled by the WebDAV module while continuing with RBAC?

My $0.02.

**Comment by picman** [comment] 2017-02-07 09:49
RBAC is in plan. v1.6.0 probably.

**Comment by picman** [comment] 2017-04-07 13:46
I've just committed the first version. In the folder details form you can define roles or users for which the folder is visible. Test in devel-1.6.0 if you can.

**Comment by picman** [comment] 2017-04-07 13:49
Duplicates #170.

**Comment by flybyray** [comment] 2017-04-30 23:08
@picman thanks for your work!

i believe this commit introduces a new bug. if i create a folder with some permissions, the admin user will see it x-times (maybe for each permission)
![Sample](http://imgur.com/PRXmFAnl.png)

**Comment by picman** [comment] 2017-05-02 11:02
I cannot reproduce your issue. Could you provide more details. I've tried this:

1) As a manager I've created folder1 with permissions for the Manager role.
2) Re-login as an administrator. I saw just one folder1

1) As a manager I've created folder2 with permissions for the logged user
2) Re-login as an administrator. I saw just one folder2

**Comment by flybyray** [comment] 2017-05-07 10:31
Hm I do not know how to describe it. I just created a folder as admin with some additional permission config.
https://www.screencast.com/t/PUo6NKdQ0I

i checked only the above commit:
"@picman	Access rights to read (maybe write) individual folders #639			4197465"

i will try it with the current devel branch again.

**Comment by picman** [comment] 2017-05-09 11:26
Just tried exactly what I see in your video and it works as expected. Please try it with the latest 1.6.0-devel.

**Comment by flybyray** [comment] 2017-06-14 18:06
Ok Thanks the folder setup is working now.

Maybe you know Play With Docker? This is a fast jumpstart setup:

http://play-with-docker.com/?stack=https:/gist.githubusercontent.com/flybyray/f9314e0dc0961c95e660359f9a6c89a4/raw/4ad8d19f3c0c7a8df7e07eca53250fa382e3184f/stack.yml

Dockerfile (flybyray/myredmine2) and entrypoint Skript
https://gist.github.com/flybyray/5d0eb07d277780359022668ab3fac14d

**Closed** 2017-08-04 08:56 UTC
Labels: duplicate
