### ISSUE TITLE
Privileges while creating a project

### ISSUE THREAD

**Issue by Rocksau80** [danmunn/redmine_dmsf#1456] opened 2023-06-12 14:02 UTC
We just ran into an strange error:
I enabled DMS as standard module for all new projects. If normal users than try to create a new project they end up with the message "Enabled modules not valid"
![image](https://github.com/danmunn/redmine_dmsf/assets/111526466/62773b74-a3cc-4633-a658-510d5fb8e5ed)
As an administrator I can create new projects without problem.

So I removed DMS as a standard for new projects and now users can create projects and can also activate the DMS module after the project is created.

**Comment by picman** [comment] 2023-06-16 08:51
I cannot reproduce the error. What are the Redmine and DMSF versions? Any others plugin installed? What does say the _production.log_?

**Comment by picman** [comment] 2023-07-14 07:40
No feedback => closing

**Closed by picman** 2023-07-14 07:40 UTC
Labels: invalid
