### ISSUE TITLE
"Project cannot be blank" error when save issue with dmsf link

### ISSUE THREAD

**Issue by RockyUs** [danmunn/redmine_dmsf#1029] opened 2019-08-03 00:18 UTC
I tried to link the document from the issue by selecting "Link From" hyperlink in issue-> document. 
I can select the documents and it does display on the issue form. But when I click the Submit to save the changing for the issue, the document does not link to the issue. And there is error: "Project cannot be blank". 

Redmine 3.4.11
DMSF 1.6.2
Ruby 2.3 x64
Windows 2012
SQl Server 2016 database

Any idea? Thanks.

**Comment by picman** [comment] 2019-08-09 06:27
It has been already fixed. Upgrade to the latest version.

**Comment by Drexlin** [comment] 2020-02-10 17:56
Hi @picman 
I'm having the same issue on my server. Which commit is this a duplicate of? I'm trying to find out what the actual code change is so that I can maybe apply it myself.

Thanks.

Redmine 3.4.4
DMSF 1.6.2

**Comment by picman** [comment] 2020-02-11 07:25
I'm sorry, but I don't remember and obviously omitted to mention here which issue is duplicated. Post the error from the production.log.

**Comment by Drexlin** [comment] 2020-02-12 15:23
Thanks @picman ...

I don't see any errors in the production.log, but here is the Parameter set that is passed when I press Submit:

```
  Parameters: {"utf8"=>"?", "authenticity_token"=>"TOKEN", "form_update_triggered_by"=>"", "issue"=>{"is_private"=>"0", "project_id"=>"15", "tracker_id"=>"4", "subject"=>"Redacted Subject", "description"=>"Redacted Description.", "status_id"=>"2", "assigned_to_id"=>"5", "parent_issue_id"=>"", "start_date"=>"2019-09-06", "due_date"=>"2020-02-14", "estimated_hours"=>"", "custom_field_values"=>{"10"=>["6", "9", "7", ""]}, "notes"=>"", "private_notes"=>"0", "lock_version"=>"24"}, "dmsf_links"=>{"1000"=>""}, "last_journal_id"=>"777", "commit"=>"Submit", "id"=>"60"}
```

I've also attached a screenshot of the error I'm seeing on the Redmine GUI.

![60 - Project cannot be blank](https://user-images.githubusercontent.com/12022669/74349057-ad30d500-4d81-11ea-9edd-3cd993e22039.png)

**Comment by picman** [comment] 2020-02-13 09:13
Probably it was the following commit. Try it.
https://github.com/danmunn/redmine_dmsf/commit/6c78dbc6032dfe931d98a24556ab92139cde5744#diff-31f13b4ba7f9529d2c2a770672f6e624

**Comment by Drexlin** [comment] 2020-02-13 20:27
Thanks for the suggestion, but this patch did not work. If there is any other data I can gather, please let me know.

**Closed** 2020-12-04 12:56 UTC
Labels: duplicate
