### ISSUE TITLE
Redmine 3.4.4 and DMSF 1.6.0, can't view attached documents in issues.

### ISSUE THREAD

**Issue by vDorst** [danmunn/redmine_dmsf#843] opened 2018-03-19 16:22 UTC
I recently upgrade Redmine 3.3.4 - >3.4.4 and DMSF 1.5.9 ->1.6.0.

But I can't view attach documents in issue any more. Returns 403 as Admin or user.
I can "browse" thru the .Issue folders and find the file. But I can't open it.

Page text
```
403

You are not authorized to access this page.
```

Production log:
```
Started GET "/dmsf/files/563/view" for 192.168.11.175 at 2018-03-19 16:42:48 +0100
Processing by DmsfFilesController#view as HTML
  Parameters: {"id"=>"563"}
  Current user: r.v.dorst (id=7)
  Rendered common/error.html.erb within layouts/base (0.1ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_html_header.html.erb (0.0ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (0.2ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_headers.html.erb (0.3ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_scrum_tips.html.erb (1.8ms)
  Rendered plugins/redmine_wiki_extensions/app/views/wiki_extensions/_body_bottom.html.erb (0.0ms)
  Rendered plugins/clipboard_image_paste/app/views/clipboard_image_paste/_add_form.html.erb (1.6ms)
Filter chain halted as :authorize rendered or redirected
Completed 403 Forbidden in 46ms (Views: 40.1ms | ActiveRecord: 3.4ms)
```

**Comment by picman** [comment] 2018-03-20 13:06
Please check **Act as attachable** = _DMS & Files_ in Project's settings/DMS.

**Comment by vDorst** [comment] 2018-03-20 15:06
Project Preferences: Act as attachable = Files & DMS.

![dms project settings](https://user-images.githubusercontent.com/2149253/37662832-3ef4663e-2c58-11e8-8a1c-678859ebd458.png)

Here are more screenshots of Project and plugins settings.

![redmine roles developer settings](https://user-images.githubusercontent.com/2149253/37662830-3ebb1bcc-2c58-11e8-89fc-101400215213.png)
![dms plugins settings](https://user-images.githubusercontent.com/2149253/37662831-3edad912-2c58-11e8-83c0-89e078434ddb.png)

**Comment by picman** [comment] 2018-03-23 10:53
If you add **Display system folders** permission?

**Comment by vDorst** [comment] 2018-03-23 13:20
Nope doesn't work.

Newly added files does work.

IJK2 behuizing.jpg is in issue 2250, old file before the update
AD5412_5422.pdf is in issue 2941, newly added file after the update.
Both in the same project and issue tracker.

So I looked in the mysql database and I notice that a old file has project_id which is equal to issue number
New file project_id is not equal to the issue number and also way lower than previous one.
Maybe this is total unrelated?

```
mysql> select * from dmsf_files where id=578 or id=431;
+-----+------------+----------------+--------------------+--------------+---------+--------------------+---------------------+---------------------+
| id  | project_id | dmsf_folder_id | name               | notification | deleted | deleted_by_user_id | created_at          | updated_at          |
+-----+------------+----------------+--------------------+--------------+---------+--------------------+---------------------+---------------------+
| 431 |       2250 |            122 | IJK2 behuizing.jpg |            1 |       0 |               NULL | 2017-11-21 09:43:38 | 2018-03-16 14:20:54 |
| 578 |        173 |            148 | AD5412_5422.pdf    |            1 |       0 |               NULL | 2018-03-23 14:00:30 | 2018-03-23 14:00:30 |
+-----+------------+----------------+--------------------+--------------+---------+--------------------+---------------------+---------------------+
```

```
mysql> select * from dmsf_file_revisions where dmsf_file_id=431 or dmsf_file_id=578;
+------+--------------+------------------------------+--------------------+-------------------------------------+---------+-----------------+----------------+-------------+----------+---------------+---------------+---------+---------+--------------------+---------+---------------------+---------------------+------------------+---------------------------+---------------------------+--------------------------+--------------------------+----------------------------------+
| id   | dmsf_file_id | source_dmsf_file_revision_id | name               | disk_filename                       | size    | mime_type       | title          | description | workflow | major_version | minor_version | comment | deleted | deleted_by_user_id | user_id | created_at          | updated_at          | dmsf_workflow_id | dmsf_workflow_assigned_by | dmsf_workflow_assigned_at | dmsf_workflow_started_by | dmsf_workflow_started_at | digest                           |
+------+--------------+------------------------------+--------------------+-------------------------------------+---------+-----------------+----------------+-------------+----------+---------------+---------------+---------+---------+--------------------+---------+---------------------+---------------------+------------------+---------------------------+---------------------------+--------------------------+--------------------------+----------------------------------+
|  905 |          431 |                         NULL | IJK2 behuizing.jpg | 171121094338_431_IJK2_behuizing.jpg |  222395 | image/jpeg      | IJK2 behuizing | schets      |     NULL |             0 |             0 | NULL    |       0 |               NULL |      19 | 2017-11-21 09:43:38 | 2017-11-21 09:43:38 |             NULL |                      NULL | NULL                      |                     NULL | NULL                     | fbd6a673902fa407d7b6e60a4141757f |
| 1124 |          578 |                         NULL | AD5412_5422.pdf    | 180323140030_578_AD5412_5422.pdf    | 1226102 | application/pdf | AD5412 5422    |             |     NULL |             0 |             1 | NULL    |       0 |               NULL |       7 | 2018-03-23 14:00:30 | 2018-03-23 14:00:30 |             NULL |                      NULL | NULL                      |                     NULL | NULL                     | 38097629b12b5a629b2df575269fc87a |
+------+--------------+------------------------------+--------------------+-------------------------------------+---------+-----------------+----------------+-------------+----------+---------------+---------------+---------+---------+--------------------+---------+---------------------+---------------------+------------------+---------------------------+---------------------------+--------------------------+--------------------------+----------------------------------+
```

Both file are on the disk 
```
root@redmine01:/data/webapps/redmine/redmine-git/files/dmsf# ll 2017/11/171121094338_431_IJK2_behuizing.jpg
-rw-r--r-- 1 redmine redmine 222395 Nov 21 09:41 2017/11/171121094338_431_IJK2_behuizing.jpg
root@redmine01:/data/webapps/redmine/redmine-git/files/dmsf# md5sum 2017/11/171121094338_431_IJK2_behuizing.jpg
fbd6a673902fa407d7b6e60a4141757f  2017/11/171121094338_431_IJK2_behuizing.jpg

root@redmine01:/data/webapps/redmine/redmine-git/files/dmsf# md5sum 2018/03/180323140030_578_AD5412_5422.pdf
38097629b12b5a629b2df575269fc87a  2018/03/180323140030_578_AD5412_5422.pdf
root@redmine01:/data/webapps/redmine/redmine-git/files/dmsf# ll 2018/03/180323140030_578_AD5412_5422.pdf
-rw-r--r-- 1 redmine redmine 1226102 Mar 23 14:00 2018/03/180323140030_578_AD5412_5422.pdf
```

**Comment by picman** [comment] 2018-03-23 13:41
Hm, that's wrong. I think, that the only way how to fix it will be manual update of related records in your database. So please replace the issue's id with project's id in `dmsf_files.project_id` column.
You do a mass update that eg. this way:

```sql
update dmsf_files f 
set f.project_id = (select d.project_id from dmsf_folders d where d.id = f.dmsf_folder_id and d.system = 1) 
where (select dmsf_folders.system from dmsf_folders where dmsf_folders.id = f.dmsf_folder_id) = 1;
```

**Comment by vDorst** [comment] 2018-03-23 14:02
Yes that works!.
Now it is fixed. Thanks.

**Comment by picman** [comment] 2018-03-26 11:09
I've just tested it but I'm not able to reproduce your case, I'm afraid. The _.Issues_ folder is not visible if the permission **Display system folders** is missing. Could you test it again, please? Isn't your user an administrator?

**Comment by vDorst** [comment] 2018-03-28 10:58
I can't see .Issues folder is my user is a normal user. Changing it back to Admin and .Issue folder is back.

**Comment by picman** [comment] 2018-03-28 11:35
An administrator see everything independently on the roles & permissions => closing.

**Comment by mrazek** [comment] 2018-06-13 19:38
I am not sure if it is caused by DMS plugin, however seems very similar to this issue. I cannot uplod Files to issues and into Files tab in project (I am able to upload Documents, which are stored in .Issue folder in dmsf). I am using APIJS plugin as well, which might be an issue, but it does not work even if I switch APIJS off....

![image](https://user-images.githubusercontent.com/12605987/41373715-69728eae-6f51-11e8-9913-3a89b406af83.png)

Saving attachment '/opt/redmine/current/files/2018/06/180613213240_3bludistaci.jpeg' (9242 bytes)
APIJS::AttachmentPatch#update_date: exiftool -FastScan -IgnoreMinorErrors -DateTimeOriginal -S3 /opt/redmine/current/files/2018/06/180613213240_3blu$
  Rendered attachments/upload.js.erb (0.6ms)
Completed 200 OK in 120ms (Views: 4.7ms | ActiveRecord: 35.9ms)

Rendered plugins/redmine_apijs/app/views/attachments/_form.html.erb (2.4ms)
  Rendered files/new.html.erb within layouts/base (3.4ms)
  Rendered plugins/a_common_libs/app/views/hooks/a_common_libs/_html_head.html.erb (2.3ms)
  Rendered plugins/redmine_contacts/app/views/contacts_issues/_additional_assets.html.erb (0.6ms)
  Rendered plugins/under_construction/app/views/hooks/under_construction/_view_layouts_base_body_top.html.erb (1.4ms)
  Rendered plugins/redmine_contacts/app/views/common/_contacts_select2_data.html.erb (0.3ms)
Completed 200 OK in 134ms (Views: 94.9ms | ActiveRecord: 24.8ms)

Thanks for any hint!

**Comment by picman** [comment] 2018-06-14 07:57
I think, that this's another problem and it doesn't seem to be related to DMSF. You can check it by removing `plugins/redmine_dmsf` folder temporarily and testing files uploading without DMSF plugin.

**Comment by mrazek** [comment] 2018-06-14 10:39
OK, I will try to do some tests in the evening... Thanks for the advice.

**Closed** 2018-06-15 06:29 UTC
Labels: type: bug
