### ISSUE TITLE
Webdav request fails with 404, when a folder inside a folder, which is not the root, has the same name as a subproject

### ISSUE THREAD

**Issue by NGeb1** [danmunn/redmine_dmsf#1462] opened 2023-07-30 11:06 UTC
Hello,
I have a folder in a folder which has the same name as a subproject. These types of folders are not accessible using WebDAV and the HTTP request returns in error 404 . I did some tests and this happens no matter where in the folders tree the folder with the same name of the subproject appears. It looks like the code in the WebDAV request handler searches for a subproject even when the folder is not a direct sub folder of the project's DMSF root.
When turning on debug logging I see that the last SQL commands before the error are: 
  SELECT `projects`.* FROM `projects` WHERE (projects.status <> 9) AND `projects`.`parent_id` = <ID> AND `projects`.`identifier` = '<name of folder>' LIMIT 1
  SELECT `enabled_modules`.* FROM `enabled_modules` WHERE `enabled_modules`.`project_id` = <ID>

The subfolder doesn't have DMS enabled....

Thanks!
NGeb1

**Comment by picman** [comment] 2023-08-10 05:56
I can't reproduce it. What version of DMSF do you use?. I've the following structure:

> project c1
>> sub-project c123
>> sub-folder Validation
>>> sub-folder c123

1. test with command line WebDAV client cadaver:

```shell
$ cadaver http://localhost:3000/dmsf/webdav/c1
dav:/dmsf/webdav/c1/> ls
Listing collection `/dmsf/webdav/c1/': succeeded.
Coll:   [c132]                              4096  led 26  2023
Coll:   Validation                          4096  led 12  2023
dav:/dmsf/webdav/c1/> cd Validation 
dav:/dmsf/webdav/c1/Validation/> ls
Listing collection `/dmsf/webdav/c1/Validation/': succeeded.
Coll:   c123                                4096  srp 10 07:45
dav:/dmsf/webdav/c1/Validation/> cd c123
dav:/dmsf/webdav/c1/Validation/c123/> ls
Listing collection `/dmsf/webdav/c1/Validation/c123/': succeeded.
        maintenance_report_cw32.odt        97808  srp 10 07:45
dav:/dmsf/webdav/c1/Validation/c123/> 
```

2. test with Gnome Files
![image](https://github.com/danmunn/redmine_dmsf/assets/779003/d4ae2ab0-1b46-4301-8820-f5dfbd910353)

**Comment by picman** [comment] 2023-10-04 10:15
No feedback => closing.

**Closed by picman** 2023-10-04 10:15 UTC
Labels: type: bug, invalid
