### ISSUE TITLE
Cannot view workflow summary from documents table

### ISSUE THREAD

**Issue by pskillen** [danmunn/redmine_dmsf#1167] opened 2020-08-27 15:04 UTC
# Bug

Cannot view the workflow summary popup when clicking a workflow status in the documents table

This appears to be caused by a malformed URL in the AJAX request - if the workflow ID is 6, the URL becomes `6.0`:

`XHR GET https://[server]/dmsf_workflows/6.0/log?dmsf_file_id=1206&project_id=3`

# Screenshot

**Expected result**  
![image](https://user-images.githubusercontent.com/1828517/91459763-ee508880-e87e-11ea-9e03-9aa02c1592c1.png)

**Actual result**  
(nothing)

# Steps to reproduce

1. Create an approval workflow in DMS
2. Create any document in DMS
3. Assign the approval workflow to document
4. Click the workflow status link in the "Workflow" column of the documents table
5. Nothing happens - see error in console

# Environment

* Redmine 4.1 (from official Docker image)
* DMSF 2.4.4
* Chrome and Firefox

**Comment by pskillen** [comment] 2020-08-27 15:05
Again, my Ruby is terrible or I'd provide you with a patch

**Comment by picman** [comment] 2020-09-09 11:19
Cannot reproduce that. It works fine in Firefox and in Chrome as well. The cause might be out of this plugin.

**Comment by picman** [comment] 2020-09-11 11:20
Lines 185-186 are related to folders. Worflows can be assigned only to files. So, `DmsfQuery::dmsf_files_scope`, and there is no `cast` just `select`:

```sql
dmsf_file_revisions.dmsf_workflow_id AS workflow_id,
```
I seems that from some reason, it return 6.0 instead of 6. I'd check the valuses directly in the database first.

```sql
SELECT workflow_id FROM dmsf_file_revisions;
```

**Comment by picman** [comment] 2020-09-24 07:50
No feedback => closing.

**Closed by picman** 2020-09-24 07:50 UTC
Labels: type: bug, wontfix
